### ISSUE TITLE
Reproducible

### ISSUE THREAD

**Issue by alienzj** [noambar/SerumMetabolomePredictions#1]
Hi, 
Where do I need to start to reproduce this analysis ?

**Comment by alienzj** [comment]
Hi,  Noam, from the [Supplementary Tables](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-020-2896-2/MediaObjects/41586_2020_2896_MOESM3_ESM.xlsx), I can't found Table 1 - 4.

**Comment by alienzj** [comment]
Hi, Noam,

How can I establish a correspondence between the input files in the notebook and the [Supplementary Tables](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-020-2896-2/MediaObjects/41586_2020_2896_MOESM3_ESM.xlsx) of the [article](https://doi.org/10.1038/s41586-020-2896-2), so as to reproduce your research ?

Looking forward your reply.

**Comment by noambar** [comment]
Hi,

To reproduce the results of the study you should refer to the raw metabolomics, phenotype and metagenomics data. See the data availability section in the manuscript. You'll need to contact Prof. Eran Segal at eran.segal@weizmann.ac.il to get the access.

If you are referring to a specific analysis which its data is included in the supplementary tables, please let me know and I'll help with the correspondence.

**Comment by alienzj** [comment]
OK,
Thanks very much.
